apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: y9zrqldxc-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-39cf9c5ff1.tqau.p3.openshiftapps.com/rhtap/rhtap-qe:0cc30c00f1f6f57cc13a392297b90607634b9e65@sha256:b6dae985692c1c80e43d73c06489d74dd81262e401280385703323f88b9856e8
        name: container-image  
